[package]
authors = ["Zhiting Zhu"]
build = "build.rs"
name = "rust-bpf"
version = "0.1.0"

[build-dependencies]
bindgen = "0.31.0"

[dependencies]
syscall = "0.2.1"
libc = "0.2.29"
byteorder = "1.1.0"
elf = "0.0.10"
nix = "0.9.0"
regex = "0.2"
lazy_static = "0.2"
bcc-sys = "0.3"
num_cpus = "1.0"
