[package]
authors = ["Zhiting Zhu"]
build = "build.rs"
name = "rust-bcc"
version = "0.1.0"

[build-dependencies]
bindgen = "0.29.0"

[dependencies]
syscall = "0.2.1"
libc = "0.2.29"
byteorder = "1.1.0"
